name: Branch Name Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF}
          DESTINATION=${GITHUB_BASE_REF}
          echo "Branch name: $BRANCH_NAME"
          echo "Destination branch: $DESTINATION"

          if [ "$DESTINATION" = "main" ]; then
            ALLOWED_PREFIXES=("release/" "hotfix/")
            echo "Destination is main. Allowed prefixes: ${ALLOWED_PREFIXES[*]}"
          elif [ "$DESTINATION" = "development" ]; then
            ALLOWED_PREFIXES=("warmfix/" "feature/" "docs/")
            echo "Destination is development. Allowed prefixes: ${ALLOWED_PREFIXES[*]}"
          else
            echo "Unknown destination branch: $DESTINATION"
            exit 1
          fi

          VALID=false
          for PREFIX in "${ALLOWED_PREFIXES[@]}"; do
            if [[ $BRANCH_NAME == $PREFIX* ]]; then
              VALID=true
              break
            fi
          done

          if [ "$VALID" = false ]; then
            echo "Error: For destination '$DESTINATION', branch name must start with one of the following prefixes: ${ALLOWED_PREFIXES[*]}"
            echo "Your branch name: $BRANCH_NAME"
            exit 1
          fi

          echo "Branch name is valid!"
