name: PR Comment Trigger for Manual Workflow
on:
  issue_comment:
    types: [created]

# Explicitly set permissions for the GITHUB_TOKEN
permissions:
  contents: read
  actions: write
  pull-requests: write

jobs:
  trigger-workflow:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '!ANTS' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Manual Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'manual-trigger.yml',
              ref: 'main',
              inputs: {
                reason: 'Triggered by PR comment !ANTS'
              }
            })
