name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  spread:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: say hello
      if: contains(github.event.comment.body, '!ANTS')
      run: |
        echo "I want to die"